services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data/tunnl-data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3002:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
  web:
    build:
      context: webapp
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
    restart: unless-stopped
  publisher:
    build:
      context: publisher
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "127.0.0.1:3444:3444"
    volumes:
      - ./publisher.log:/app/publisher.log
    env_file:
      - .env
    restart: unless-stopped
