http:
  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
  routers:
    publisher-router:
      rule: 'HOST(`publisher.ROOT_DOMAIN`)'
      service: publisher-service
      entryPoints:
        - tcp_tls
      tls:
        certResolver: letsencrypt
        domains:
          - main: "*.ROOT_DOMAIN" 
    tunnl-router:
      rule: 'HOST(`ROOT_DOMAIN`)'
      service: tunnl-service
      entryPoints:
        - tcp_tls
      tls:
        certResolver: letsencrypt
        domains:
          - main: "ROOT_DOMAIN" 
    keycloak-router:
      rule: 'HOST(`auth.ROOT_DOMAIN`)'
      service: keycloak-service
      entryPoints:
        - tcp_tls
      tls:
        certResolver: letsencrypt
        domains:
          - main: "*.ROOT_DOMAIN" 
    ziti-router:
      rule: 'HOST(`ziti.ROOT_DOMAIN`)'
      service: http-controller-service
      entryPoints:
        - tcp_tls
      tls:
        certResolver: letsencrypt
        domains:
          - main: "*.ROOT_DOMAIN" 
  services:
    http-controller-service:
      loadBalancer:
        serversTransport: insecureTransport
        servers:
          - url: "https://127.0.0.1:10443"
    keycloak-service:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8080"
    tunnl-service:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:3000"
    publisher-service:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:3444"
tcp:
  routers:
    controller-router:
      entryPoints:
        - tcp_tls
      rule: "HostSNI(`ctrl.ziti.ROOT_DOMAIN`)"
      service: controller-service
      tls:
        passthrough: true
    edge-router:
      entryPoints:
        - tcp_tls
      rule: "HostSNI(`er1.ziti.ROOT_DOMAIN`)"
      service: edge-service
      tls:
        passthrough: true
  services:
    controller-service:
      loadBalancer:
        servers:
          - address: 127.0.0.1:10443
    edge-service:
      loadBalancer:
        servers:
          - address: 127.0.0.1:11443
