http:
  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
  routers:
    publisher-router:
      rule: 'HOST(`publisher.ROOT_DOMAIN`)'
      service: publisher-service
      entryPoints:
        - websecure
      tls: {}
    tunnl-router:
      rule: 'HOST(`TUNNL_DOMAIN`)'
      service: tunnl-service
      entryPoints:
        - websecure
      tls: {}
    keycloak-router:
      rule: 'HOST(`auth.ROOT_DOMAIN`)'
      service: keycloak-service
      entryPoints:
        - websecure
      tls: {}
    ziti-router:
      rule: 'HOST(`ziti.ROOT_DOMAIN`)'
      service: http-controller-service
      entryPoints:
        - websecure
      tls: {}
  services:
    http-controller-service:
      loadBalancer:
        serversTransport: insecureTransport
        servers:
          - url: "https://ctrl.ziti.ROOT_DOMAIN:443"
    keycloak-service:
      loadBalancer:
        servers:
          - url: "http://keycloak:8080"
    tunnl-service:
      loadBalancer:
        servers:
          - url: "http://web:3000"
    publisher-service:
      loadBalancer:
        servers:
          - url: "http://publisher:3444"
tcp:
  routers:
    controller-router:
      entryPoints:
        - websecure
      rule: "HostSNI(`ctrl.ziti.ROOT_DOMAIN`)"
      service: controller-service
      tls:
        passthrough: true
    edge-router:
      entryPoints:
        - websecure
      rule: "HostSNI(`er1.ziti.ROOT_DOMAIN`)"
      service: edge-service
      tls:
        passthrough: true
  services:
    controller-service:
      loadBalancer:
        servers:
          - address: ctrl.ziti.ROOT_DOMAIN:443
    edge-service:
      loadBalancer:
        servers:
          - address: er1.ziti.ROOT_DOMAIN:443

