http:
  middlewares:
    redirect-to-root:
      redirectRegex:
        regex: "^https?://www\\.tunnl\\.app(.*)"
        replacement: "https://tunnl.app$1"
        permanent: true

  routers:
    tunnl-router:
      rule: "Host(`tunnl.app`)"
      service: tunnl-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    install-file:
      rule: "Host(`tunnl.app`) && Path(`/install.sh`)"
      service: file-server
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    quickstart-file:
      rule: "Host(`tunnl.app`) && Path(`/quickstart.tar.xz`)"
      service: file-server
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver

    www-router:
      rule: "Host(`www.tunnl.app`)"
      service: tunnl-service
      entryPoints:
        - websecure
      middlewares:
        - redirect-to-root
      tls:
        certResolver: letsencrypt

  services:
    tunnl-service:
      loadBalancer:
        servers:
          - url: "http://landing:3000"
    file-server:
      loadBalancer:
        servers:
          - url: "http://file-server:80"
